const products = {
  1: {
    name: "Sản phẩm 1",
    namekodau: "sp1",
    price: "100.000",
    img: "../IMG/SanPham01.jpg",
    description:
      "Đây là mô tả chi tiết về sản phẩm 1. Sản phẩm chất lượng cao, phù hợp với nhu cầu của bạn.",
  },
  2: {
    name: "Sản phẩm 2",
    namekodau: "sp2",
    price: "150.000",
    img: "../IMG/SanPham02.jpg",
    description: "Mô tả chi tiết về sản phẩm 2. Thiết kế đẹp, chất liệu bền.",
  },
  3: {
    name: "Sản phẩm 3",
    namekodau: "sp3",
    price: "200.000",
    img: "../IMG/SanPham03.jpg",
    description: "Sản phẩm 3 với nhiều tính năng ưu việt, giá trị vượt trội.",
  },
  4: {
    name: "Sản phẩm 4",
    namekodau: "sp4",
    price: "180.000",
    img: "../IMG/SanPham04.jpg",
    description: "Sản phẩm 4 với thiết kế hiện đại, tiện lợi và dễ sử dụng.",
  },
  5: {
    name: "Sản phẩm 5",
    namekodau: "sp5",
    price: "250.000",
    img: "../IMG/SanPham05.jpg",
    description: "Sản phẩm 5 cao cấp với nhiều tính năng độc đáo và hấp dẫn.",
  },
  6: {
    name: "Sản phẩm 6",
    namekodau: "sp6",
    price: "120.000",
    img: "../IMG/SanPham06.jpg",
    description: "Sản phẩm 6 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  7: {
    name: "Sản phẩm 7",
    namekodau: "sp7",
    price: "120.000",
    img: "../IMG/SanPham07.jpg",
    description: "Sản phẩm 7 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  8: {
    name: "Sản phẩm 8",
    namekodau: "sp8",
    price: "120.000",
    img: "../IMG/SanPham08.jpg",
    description: "Sản phẩm 8 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  9: {
    name: "Sản phẩm 9",
    namekodau: "sp9",
    price: "120.000",
    img: "../IMG/SanPham09.jpg",
    description: "Sản phẩm 9 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  10: {
    name: "Sản phẩm 10",
    namekodau: "sp10",
    price: "90.000",
    img: "../IMG/SanPham10.jpg",
    description: "Sản phẩm 10 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  11: {
    name: "Sản phẩm 11",
    namekodau: "sp11",
    price: "120.000",
    img: "../IMG/SanPham11.jpg",
    description: "Sản phẩm 11 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  12: {
    name: "Sản phẩm 12",
    namekodau: "sp12",
    price: "120.000",
    img: "../IMG/SanPham12.jpg",
    description: "Sản phẩm 12 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  13: {
    name: "Sản phẩm 13",
    namekodau: "sp13",
    price: "120.000",
    img: "../IMG/SanPham13.jpg",
    description: "Sản phẩm 13 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  14: {
    name: "Sản phẩm 14",
    namekodau: "sp14",
    price: "120.000",
    img: "../IMG/SanPham14.jpg",
    description: "Sản phẩm 14 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  15: {
    name: "Chậu 1",
    namekodau: "spc1",
    price: "100.000",
    img: "../IMG/Chậu 1.jpg",
    description: "Sản phẩm chậu 1 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  16: {
    name: "Chậu 2",
    namekodau: "spc2",
    price: "100.000",
    img: "../IMG/Chậu 2.jpg",
    description: "Sản phẩm chậu 2 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  17: {
    name: "Chậu 3",
    namekodau: "spc3",
    price: "100.000",
    img: "../IMG/Chậu 3.jpg",
    description: "Sản phẩm chậu 3 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  18: {
    name: "Chậu 4",
    namekodau: "spc4",
    price: "100.000",
    img: "../IMG/Chậu 4.png",
    description: "Sản phẩm chậu 4 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  19: {
    name: "Chậu 5",
    namekodau: "spc5",
    price: "100.000",
    img: "../IMG/Chậu 5.png",
    description: "Sản phẩm chậu 5 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  20: {
    name: "Chậu 6",
    namekodau: "spc6",
    price: "100.000",
    img: "../IMG/Chậu 6.png",
    description: "Sản phẩm chậu 6 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  21: {
    name: "Chậu 7",
    namekodau: "spc7",
    price: "100.000",
    img: "../IMG/Chậu 7.png",
    description: "Sản phẩm chậu 7 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  22: {
    name: "Chậu 8",
    namekodau: "spc8",
    price: "100.000",
    img: "../IMG/Chậu 8.png",
    description: "Sản phẩm chậu 8 phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  23: {
    name: "Combo Nhật Cảnh Hoàng Kim",
    namekodau: "spcombo1",
    price: "199.000",
    img: "../IMG/Combo Hago.png",
    description: "Sản phẩm Combo Nhật Cảnh Hoàng Kim phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  24: {
    name: "Combo Hoàng Kim Tỏa Sắc",
    namekodau: "spcombo2",
    price: "299.000",
    img: "../IMG/Combo Hago 2.png",
    description: "Sản phẩm Combo Hoàng Kim Tỏa Sắc phù hợp với mọi nhu cầu, giá cả phải chăng.",
  },
  25: {
    name: "Combo Hồng Lam Mộng",
    namekodau: "spcombo3",
    price: "219.000",
    img: "../IMG/Combo Hago 3.png",
    description: "Sản phẩm Combo Hồng Lam Mộng phù hợp với mọi nhu cầu, giá cả phải chăng.",
  }
};
